### ISSUE TITLE
Feedback - Week 13 Assignment

### ISSUE THREAD

**Issue by ntuvera** [Alexg2195/alex-portfolio#11]
Hey @Alexg2195, how's it going?  I tried to checkout your portfolio page and cloned your repo...

I see you've started to build your server and got some static routes setup.  Your routes are good, but you need to fix your links in your html pages to reflect the new routes.

We'll also need to add those `app.use`s you've commented out to allow your assets (images in this case) to be hosted and displayed on local/Heroku.

Also you're missing Dynamic routes and some session basics middleware.  If you're having any hangups feel free to message me or Albert about it.  Or if you wanna talk about it here, anything holding you up or was it a matter of time?  Eitherway LMK.

Good Luck on Project Week :)

**Comment by Alexg2195** [comment]
@ntuvera Hi Nate yes I only started my portfolio been really working on a side projects and a lot of just trying to make sure our group project is going well and where it needs to be as well. I'm not really stuck on anything atm just need more time in the days hahaha. Thank you for the feed back!

**Comment by Alexg2195** [comment]
Cleaning up old github issues
